version: '3'

services:
    postgres:
        image: postgres:alpine
        container_name: postgres
        env_file: .env
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}

    joplin:
        image: joplin/server:latest
        container_name: joplin
        env_file: .env
        depends_on:
            - postgres
        restart: unless-stopped
        environment:
            - APP_PORT=${APP_PORT}
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_HOST=postgres

    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - "22300:22300"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
